### ISSUE TITLE
Heatmap2 can't be found in tool panel

### ISSUE THREAD

**Issue by mblue9** [usegalaxy-eu/usegalaxy-eu-tools#124]
Hello,

Our users need to use heatmap2 for the workshop but if I search for it in the .eu tool panel I can't find it. It's definitely there as my ugly workaround was to open the history multi-panel, find a history where I used it previously, drag that dataset into the current history, then use the rerun button to run it on the current dataset.

Is it related to having a "+" in the version? If so would adding commit #6737 fix it?

From https://github.com/galaxyproject/galaxy/issues/6724:
>Works for us on 18.05 with the inclusion of #6737 .

**Comment by bebatut** [comment]
You can find it in the first "graph / display data" of the last section in the tool panel ("other tools")

**Comment by mblue9** [comment]
Ah thanks! 

What about fixing this generally though for people who don't know to look for it in that category? 

And same issue exists for hisat (can't be found in tool panel search) so maybe affects all tools with "+"?

**Comment by erasche** [comment]
Yes this will hopefully be fixed with latest 18.05 / that issue that we reported that you've linked.

Unfortunately, given past experiences, we will not be upgrading in the next week or so due to ongoing courses and our policy of freezing for those so as to not cause any potential outages when people are especially depending our service to be up.

We will move to a new head node and will upgrade as a part of that move.

**Comment by mblue9** [comment]
Ok thanks for the info.
