### ISSUE TITLE
Copy Link of tools does not work as intended

### ISSUE THREAD

**Issue by kostrykin** [usegalaxy-eu/usegalaxy-eu-tools#570]
When clicking on the "Copy Link" menu option of an arbitrary tool, for example

<img width="722" alt="Bildschirm­foto 2023-04-14 um 16 38 43" src="https://user-images.githubusercontent.com/6557139/232075382-87937145-d395-4866-a3a5-8a05bc36e124.png">

and then opening the copied link in a different web browser, the tool is not loaded and an error occurs:

> Loading tool CONVERTER_biom failed: History unavailable. Please specify a valid history id

The name of the tool in the message varies depending on the tool being used.

Is there any possibility of creating a working link to a tool, which one could, e.g., transmit to someone else?

**Comment by wm75** [comment]
Interesting. I just tested and this only happens if you are not logged in to any account in the other browser and have no existing anonymous session there either.
Even then, if you try the same link again after the initial error it seems to work.

Definitely a bug, but few people will ever experience it.

**Comment by bgruening** [comment]
@ElectronicBlueberry @itisAliRH can you please look at this one?

**Comment by davelopez** [comment]
We had a quick look at this, and the reason for failing the request seems to be related to the ordering of how the page is loading the components now. For anonymous users, the history component loads **after** this request, meaning the default anonymous history gets created in the server only after the history component load triggers it. Once the default history is associated with the session everything works as expected that's why just a simple refresh of the page after the error works.

**Comment by davelopez** [comment]
This is now tracked in the main Galaxy repository https://github.com/galaxyproject/galaxy/issues/16063
